export enum Protocol {
  SDT = 1,
  DMP,
}

export enum SDTVector {
  REL_WRAP = 1,
  UNREL_WRAP,
  CHANNEL_PARAMS,
  JOIN,
  JOIN_REFUSE,
  JOIN_ACCEPT,
  LEAVE,
  LEAVING,
  CONNECT,
  CONNECT_ACCEPT,
  CONNECT_REFUSE,
  DISCONNECT,
  DISCONNECTING,
  ACK,
  NAK,
  GET_SESSIONS,
  SESSIONS,
}

export enum DMPVector {
  GET_PROPERTY = 1,
  SET_PROPERTY,
  GET_PROPERTY_REPLY,
  EVENT,
  RESERVED_1,
  RESERVED_2,
  SUBSCRIBE,
  UNSUBSCRIBE,
  GET_PROPERTY_FAIL,
  SET_PROPERTY_FAIL,
  RESERVED_3,
  SUBSCRIBE_ACCEPT,
  SUBSCRIBE_REJECT,
  RESERVED_4,
  RESERVED_5,
  RESERVED_6,
  SYNC_EVENT,
}

export enum TransportLayerAddressType {
  SDT_ADDR_NULL = 0,
  SDT_ADDR_IPV4,
  SDT_ADDR_IPV6,
}

export enum SDTReasonCode {
  NONSPECIFIC = 1,
  ILLEGAL_PARAMETERS,
  LOW_RESOURCES,
  ALREADY_MEMBER,
  BAD_ADDRESS_TYPE,
  NO_RECIPROCAL_CHANNEL,
  CHANNEL_EXPIRED,
  LOST_SEQUENCE,
  SATURATED,
  TRANSPORT_ADDRESS_CHANGING,
  ASKED_TO_LEAVE,
  NO_RECIPIENT,
  ONLY_UNICAST_SUPPORTED,
}
