export enum Protocol {
  SDT = 1,
  E131 = 4,
}

export enum SDTVector {
  REL_WRAP = 1,
  UNREL_WRAP,
  CHANNEL_PARAMS,
  JOIN,
  JOIN_REFUSE,
  JOIN_ACCEPT,
  LEAVE,
  LEAVING,
  CONNECT,
  CONNECT_ACCEPT,
  CONNECT_REFUSE,
  DISCONNECT,
  DISCONNECTING,
  ACK,
  NAK,
  GET_SESSIONS,
  SESSIONS,
}

export enum TransportLayerAddressType {
  SDT_ADDR_NULL = 0,
  SDT_ADDR_IPV4,
  SDT_ADDR_IPV6,
}

export enum SDTReasonCode {
  NONSPECIFIC = 1,
  ILLEGAL_PARAMETERS,
  LOW_RESOURCES,
  ALREADY_MEMBER,
  BAD_ADDRESS_TYPE,
  NO_RECIPROCAL_CHANNEL,
  CHANNEL_EXPIRED,
  LOST_SEQUENCE,
  SATURATED,
  TRANSPORT_ADDRESS_CHANGING,
  ASKED_TO_LEAVE,
  NO_RECIPIENT,
  ONLY_UNICAST_SUPPORTED,
}
